server:
  port: 8087
---

spring:
  config:
    activate:
      on-profile: "dev"
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://localhost:8080
#          uri: http://api.yas.local
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: nextjs
          uri: http://localhost:3000
          predicates:
            - Path=/**
---

spring:
  config:
    activate:
      on-profile: "prod"
  cloud:
    gateway:
      routes:
        - id: api
          uri: http://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - TokenRelay=
        - id: nextjs
          uri: http://localhost:3000
          predicates:
            - Path=/**
